spring.application.name=gamestore

##Configuração do banco de dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# obs: nunca colocar senhas em documentos que vão para o github

## Configurações do JPA - hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
